language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
script:
- source ./environment_test.sh
- py.test
env:
  global:
  - SETTINGS=test
deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: mEZYEhSMwSQg5om22y7IIuQPNR3T6gfhWOEVDOudsUlEbxp+KqTMcD8T97/X8VlfhtdvNJM6CtdC0qWmlz+qatM+nNO2cIBPrQ9r7MRaU1brfSKhcQ/w9v3urjCzOEuq0EwvHPwC9H/BzlHPNXrgjc+ey0aGCVecx7eV5RqWT+0=
  app: lr-pull-dashboard
  on:
    repo: LandRegistry/pull-dashboard
    branch: master
